windowrule = match:class com.gabm.satty , float on , size 500 500

layerrule = match:namespace waybar, blur on
layerrule = match:namespace waybar, ignore_alpha 0.1
layerrule = match:namespace waybar, no_anim on

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-notification-window, blur on

layerrule = match:namespace swaync-control-center, animation slide right
layerrule = match:namespace swaync-notification-window, animation slide right

layerrule = match:namespace swaync-control-center, ignore_alpha 0.1
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.1

layerrule = match:namespace logout_dialog, animation fade
layerrule = match:namespace logout_dialog, blur on

layerrule = match:namespace rofi, animation slide
layerrule = match:namespace rofi, blur on
layerrule = match:namespace rofi, ignore_alpha 0.3

layerrule = match:namespace swayosd, blur on
layerrule = match:namespace swayosd, ignore_alpha 0.1
